services:
  docs:
    image: keycloak_with_multiple_roles_local_docs
    container_name: keycloak_with_multiple_roles_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./keycloak_with_multiple_roles:/app/keycloak_with_multiple_roles:z
    ports:
      - '9000:9000'
    command: /start-docs
